* added functions to handle temporary files 	  - GB_unique_filename (used pid of current process. before in most cases $ARB_PID was used, but that is only useful for arb_panic and arb_clean functionality. For normal tempfiles pid is the better choice - otherwise two processes of one ARB instance could generate the same tempfile name) 	  - GB_create_tempfile 	  - GB_fopen_tempfile 	  - GB_is_privatefile (function for testing whether tempfiles have correct permissions - especially those tempfiles pre-generated by GB_create_tempfile and overwritten later by a shell script) 	* added GB_read_fp (similar to GB_read_file, but works on open filepointer) 	* added GB_append_suffix 	* added GB_remove_on_exit (removes files at program exit) 	* rewrote all functions creating temporary files. Files are opened in private mode (user only read/write) now and are properly removed after usage or when program exits. 	* bug-fixes: 		     - GB_size_of_file(NULL) 		     - GB_split_full_path (returned name as suffix if no suffix was present. Now returns NULL) 		     - awt_get_selected_fullname returned /print.ps (instead of using cwd) 	* replaced String() by strdup() in GDE 	* fixed several calls to GB_unlink() 	* removed GB_getuid / GB_getpid 	* tweaked arb_panic (panicfile is private now! modified output and added cmd killall) 	* help-search now ignores comment lines in helpfiles 	* rewrote exporter (cause it was impossible to correctly handle tmp-files). Automatically appends suffix to outputfilename. 	* improved error handling in several functions 	* file selection boxes refresh automatically if directory modtime changes 	* When exporting frequencies from arb_phylo, dont write 3 files to tmp (of which 2 were always empty) - write only the one with content. I dont know what the file is good for, but since it is removed on exit now, it doesnt do any harm.

diff --git a/SH/arb_panic b/SH/arb_panic
--- a/SH/arb_panic
+++ b/SH/arb_panic
@@ -1,22 +1,21 @@
 #!/bin/sh
 
+umask 066 # user read/write
+
+seperator() {
+        echo "*************************************** $*"
+}
+
 err () {
-        echo "*********** ERROR **********" 1>&2
+        seperator ERROR 1>&2
         echo "`basename $0`: $@" 1>&2
         exit 1
 }
 
-seperator() {
-        echo ''
-        echo '*****************************'
-}
 
 chooser="/tmp/arb_pids_${USER}_*"
 
-echo '*****************************'
-echo "********* P A N I C *********"
-echo '*****************************'
-echo ""
+seperator PANIC
 echo "  This Module tries to save a running database"
 echo "  There may be more than one database server (ARB_NT):"
 echo "          --------------------------------"
@@ -26,6 +25,7 @@ for i in $chooser ; do
 done
 echo "          --------------------------------"
 
+seperator
 echo "Please choose one line and enter the rightmost number"
 
 read ARB_PID
@@ -34,7 +34,7 @@ if [ ! -f /tmp/arb_pids_${USER}_${ARB_PID} ]; then
 fi
 
 seperator
-echo "Please enter file name (full path):"
+echo "Please enter full path (to save DB):"
 read FILE
 
 panicfile="/tmp/arb_panic_${USER}_${ARB_PID}"
@@ -42,24 +42,46 @@ rm -f $panicfile
 echo "$FILE" >$panicfile
 ok=false
 for i in `cat /tmp/arb_pids_${USER}_${ARB_PID}`; do
-        if kill -1 $i 2>/dev/null; then
+	echo "[Sending SIGHUP to pid $i]"
+        if kill -HUP $i 2>/dev/null; then
                 ok=true
+                echo "[Process $i accepted HUP]"
                 break
         fi
 done
+
 if [ "$ok" = "false" ]; then
-        err     "Sorry could not find a running server"
+        err "Sorry could not find a running server"
 fi
 seperator
-echo "Wait until database is saved (1000 sequences == 1min ) or press <ctrl-c> to abort"
+echo "Wait until database is saved (or press <ctrl-c> to abort)"
 while [ -f $panicfile ]; do
+    echo "[waiting]"
+    sleep 1
+    if [ -f $panicfile] ; then
         sleep 1
-        echo "          waiting"
+        if [ -f $panicfile] ; then
+            sleep 1
+            if [ -f $panicfile] ; then
+                sleep 1
+                if [ -f $panicfile] ; then
+                    sleep 1        
+                fi
+            fi
+        fi
+    fi
 done
 
 seperator
-echo "enter 'kill' if you want to kill the server and its clients"
+echo "enter 'kill'    if you want to kill the server and its clients"
+echo "enter 'killall' if you want to kill ALL servers and clients"
+
 read ki
+
 if [ "$ki" = "kill" ] ; then
+    echo "[Sending SIGTERM to pid $i]"
+    kill -TERM $i
+fi
+if [ "$ki" = "killall" ] ; then
         arb_clean
 fi
