* help files triggered by GDE menus     - only helpfiles referenced in first found .menu were expected/generated (found menu was align.menu). broken by [8806]     - added missing generation of phylip.help from phylip.html     - reactivates the following files {{{ agde_DNAml_rates.hlp agde_dnaml.hlp agde_dnaml_sub_AxML_doc.hlp agde_dnaml_sub_fastDNAml_doc.hlp agde_dnapars.hlp agde_lsadt.hlp agde_phylip.hlp agde_phylip_distance.hlp agde_phylip_distance_sub_dnadist_doc.hlp agde_phylip_distance_sub_fitch_doc.hlp agde_phylip_distance_sub_kitsch_doc.hlp agde_phylip_distance_sub_neighbor_doc.hlp agde_phylip_distance_sub_protdist_doc.hlp agde_phylip_sub_dnadist_doc.hlp agde_phylip_sub_fitch_doc.hlp agde_phylip_sub_kitsch_doc.hlp agde_phylip_sub_neighbor_doc.hlp agde_phylip_sub_protdist_doc.hlp agde_phyml.hlp agde_proml.hlp agde_protpars.hlp agde_readseq.hlp agde_readseq_sub_Formats.hlp agde_readseq_sub_Readme.hlp agde_readseq_sub_Readseq_help.hlp agde_treepuzzle.hlp }}}

diff --git a/trunk/GDEHELP/Makefile.helpfiles b/trunk/GDEHELP/Makefile.helpfiles
--- a/trunk/GDEHELP/Makefile.helpfiles
+++ b/trunk/GDEHELP/Makefile.helpfiles
@@ -64,10 +64,11 @@ $(GENHELPDEST)/%.help: $(GENDOCDEST)/%.doc $(HEADER)
 # rules to generate plain doc from provided html files
 
 HELP_TREEPUZZLE=../GDE/TREEPUZZLE/doc
-HELP_PHYLIP=../GDE/PHYLIP/doc
+PHYLIP_MAIN=../GDE/PHYLIP
+HELP_PHYLIP=$(PHYLIP_MAIN)/doc
 HELP_PHYML=../GDE/PHYML
 
-FORCED_DOC_NAMES=proml dnapars protpars phyml
+FORCED_DOC_NAMES=proml dnapars protpars phyml phylip
 LYNX_PARA=-dump -nolist -display_charset=iso-8859-1
 
 $(GENDOCDEST)/%.doc: $(HELP_PHYLIP)/%.html Makefile.helpfiles
@@ -82,8 +83,12 @@ $(GENDOCDEST)/phyml.doc: $(HELP_PHYML)/usersguide_phyliplike.html Makefile.helpf
 	lynx $(LYNX_PARA) $< | $(SED) -e 's/©/(C)/' > $@
 	test -s $@ || (echo $@ not generated or empty && rm $@ && false)
 
+$(GENDOCDEST)/phylip.doc: $(PHYLIP_MAIN)/phylip.html Makefile.helpfiles
+	lynx $(LYNX_PARA) $< | $(SED) -e 's/©/(C)/' > $@
+	test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+
 FORCED_DOCS=$(addsuffix .doc,$(addprefix $(GENDOCDEST)/,$(FORCED_DOC_NAMES)))
-forcedoc: $(FORCED_DOCS)
+forcedoc: $(FORCED_DOCS) Makefile
 
 # ------------------------------------------------------------
 # default rule to raise error if no rule is given to generate a helpfile.
@@ -94,7 +99,7 @@ $(GENHELPDEST)/%.help:
 	@( test -f $(HELP_WRITTEN)/$(notdir $@) ) \
 	|| \
 	( \
-		echo "Makefile.helpfiles:18: Error: No rule to make $(notdir $@) (to which is referred to in a GDE menu)" ; \
+		echo "Makefile.helpfiles:22: Error: No rule to make $(notdir $@) (to which is referred-to inside GDE menus, see hits below)" ; \
 		grep -n $(notdir $@) MENUS/*.menu ; \
 		false )
 
