* update from 'trunk' into 'pars'     - skipping log:trunk@12967-12970,12973,12975 (parsimony loop optimization)   * adds:     - log:branches/gcc@12995:13018     - log:branches/sanitize@13023:13076     - log:branches/sativa@12886:13068     - log:trunk@12972,12977:13078

diff --git a/branches/pars/Makefile b/branches/pars/Makefile
--- a/branches/pars/Makefile
+++ b/branches/pars/Makefile
@@ -28,6 +28,12 @@
 # COVERAGE=0/1/2        compile in gcov support (useful together with UNIT_TESTS=1)
 #                       0=no, 1+2=compile in, 1=show
 # STABS=0/1             force stabs format? (0 = "use default format")
+# SANITIZE=0/#/all      use Sanitizer? (defaults to 0,
+#                                       1=AddressSanitizer+LeakSanitizer,
+#                                       2=UndefinedBehaviorSanitizer,
+#                                       combine bit-values to activate multiple Sanitizers,
+#                                       specify 'all' to activate all)
+# SHOWTODO=0/1          activate TODO-warnings? (defaults to 0, except for ralf)
 #
 # -----------------------------------------------------
 # The ARB source code is aware of the following defines:
@@ -72,12 +78,9 @@ endif
 
 export CC CXX A_CC A_CXX
 
-ifeq ($(LD_LIBRARY_PATH),'')
-LD_LIBRARY_PATH:=${ARBHOME}/lib
-endif
-
-ifeq ($(DARWIN),1)
-LD_LIBRARY_PATH:=${ARBHOME}/lib
+# unconditionally prepend $(ARBHOME)/lib to LD_LIBRARY_PATH if not found
+ifeq ($(findstring $(ARBHOME)/lib,$(LD_LIBRARY_PATH)),)
+LD_LIBRARY_PATH:=${ARBHOME}/lib:$(LD_LIBRARY_PATH)
 endif
 
 FORCEMASK = umask 002
@@ -90,13 +93,13 @@ READLINK:=$(ARBHOME)/SH/arb_readlink
 
 # supported gcc versions:
 ALLOWED_gcc_VERSIONS=\
-	4.3.1 4.3.2 4.3.3 4.3.4 \
-	4.4.1       4.4.3       4.4.5 4.4.6  4.4.7 \
-	      4.5.2 \
-	4.6.1 4.6.2 4.6.3 \
-	4.7.1 4.7.2 4.7.3 \
-	4.8.0 4.8.1 4.8.2 4.8.3 \
-	4.9.0 4.9.1 \
+        4.3.1 4.3.2 4.3.3 4.3.4 \
+        4.4.1       4.4.3       4.4.5 4.4.6  4.4.7 \
+              4.5.2 \
+        4.6.1 4.6.2 4.6.3 \
+        4.7.1 4.7.2 4.7.3 4.7.4 \
+  4.8.0 4.8.1 4.8.2 4.8.3 \
+  4.9.0 4.9.1 \
 
 # supported clang versions:
 ALLOWED_clang_VERSIONS=\
@@ -137,7 +140,7 @@ USE_GCC_452_OR_HIGHER:=
 USE_GCC_46_OR_HIGHER:=
 USE_GCC_47_OR_HIGHER:=
 USE_GCC_48_OR_HIGHER:=
-
+USE_GCC_49_OR_HIGHER:=
 
 ifeq ($(USE_GCC_MAJOR),4)
  ifeq ($(USE_GCC_MINOR),5)
@@ -152,6 +155,9 @@ ifeq ($(USE_GCC_MAJOR),4)
     USE_GCC_47_OR_HIGHER:=yes
     ifneq ($(USE_GCC_MINOR),7)
      USE_GCC_48_OR_HIGHER:=yes
+      ifneq ($(USE_GCC_MINOR),8)
+       USE_GCC_49_OR_HIGHER:=yes
+      endif
     endif
    endif
   endif
@@ -161,6 +167,7 @@ else
  USE_GCC_46_OR_HIGHER:=yes
  USE_GCC_47_OR_HIGHER:=yes
  USE_GCC_48_OR_HIGHER:=yes
+ USE_GCC_49_OR_HIGHER:=yes
 endif
 
 #---------------------- define special directories for non standard builds
@@ -187,6 +194,12 @@ clflags :=# linker flags (when passed through gcc)
 extended_warnings :=# warning flags for C and C++-compiler
 extended_cpp_warnings :=# warning flags for C++-compiler only
 
+# TEMPORARY WORKAROUND for linker issues with launchpad binutils
+# code was added to ld to check for overlapping FDEs. Since ARB
+# worked before, we want this not to fail for the moment.
+# FIXME: remove this!
+clflags += -Wl,-noinhibit-exec
+
 
 ifeq ($(DEBUG),0)
 	dflags := -DNDEBUG# defines
@@ -208,12 +221,6 @@ ifeq ($(DEBUG),1)
 	dflags := -DDEBUG
 
 	gdb_common := -g -g3 -ggdb -ggdb3
-
-ifeq ($(DEVELOPER),RALF)
- ifeq ('$(USE_GCC_48_OR_HIGHER)','yes')
-	STABS:=1
- endif
-endif
 
 DBGOPTI:=-O0
 ifeq ('$(USE_GCC_48_OR_HIGHER)','yes')
@@ -263,7 +270,17 @@ endif
 
 # ------- above only warnings available in 3.0
 
- ifneq ('$(COMPILER_VERSION)','4.7.3') # g++ crashes on GenomeImport.cxx when -Weffc++ is active (bug reported)
+WEFFC_BROKEN:=0
+ ifeq ('$(USE_GCC_47_OR_HIGHER)','yes')
+  ifneq ('$(USE_GCC_48_OR_HIGHER)','yes')
+#  -Weffc++ broken in 4.7.x series
+# gcc 4.7.3 crashes on GenomeImport.cxx when -Weffc++ is active
+# (bug reported https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56923; apparently wont be fixed for 4.7-series)
+# gcc 4.7.4 crashes on DBwriter.cxx when -Weffc++ is active
+   WEFFC_BROKEN:=1
+  endif
+ endif
+ ifeq ('$(WEFFC_BROKEN)','0')
 	extended_cpp_warnings += -Weffc++# gcc 3.0.1
  endif
 	extended_cpp_warnings += -Wmissing-noreturn# gcc 3.0.2
@@ -298,11 +315,21 @@ ifeq ($(USE_CLANG),1)
 	extended_cpp_warnings += -Wno-mismatched-tags -Wno-char-subscripts -Wno-unused-private-field -Wno-string-plus-int -Wno-gnu-static-float-init
 endif
 
+ifeq ($(USE_CLANG),0)
+# TEMPORARY WORKAROUND for linker issues with launchpad binutils
+# code was added to ld to check for overlapping FDEs. Since ARB
+# worked before, we want this not to fail for the moment.
+# FIXME: remove this!
+        clflags += -Wl,-noinhibit-exec
+endif
+
 #---------------------- developer
 
 ifneq ($(DEVELOPER),ANY) # ANY=default setting (skip all developer specific code)
 	dflags += -DDEVEL_$(DEVELOPER)# activate developer/release specific code
 endif
+
+#---------------------- activate TODO warnings?
 
 ifndef SHOWTODO
  ifeq ($(DEVELOPER),RALF)
@@ -313,6 +340,62 @@ ifndef SHOWTODO
 endif
 ifeq ($(SHOWTODO),1)
 	dflags += -DWARN_TODO# activate "TODO" warnings
+endif
+
+#---------------------- activate Sanitizers?
+
+ASAN_OPTIONS:=handle_segv=0:color=0
+ASAN_OPTIONS+=:detect_leaks=1 # comment-out to disable leak-detection
+ASAN_OPTIONS+=:check_initialization_order=1
+
+# suppressions: SOURCE_TOOLS/arb.leaksan.supp
+LSAN_OPTIONS:=max_leaks=3:suppressions=$(ARBHOME)/SOURCE_TOOLS/arb.leaksan.supp
+
+
+ifndef SANITIZE
+ SANITIZE:=0
+endif
+
+SANITIZE_ADDRESS:=0
+SANITIZE_UNDEFINED:=0
+
+ifneq ($(SANITIZE),0)
+ ifeq ($(SANITIZE),all)
+  SANITIZE:=3
+ endif
+
+ ifeq ($(SANITIZE),1)
+  SANITIZE_ADDRESS:=1
+ else
+  ifeq ($(SANITIZE),2)
+   SANITIZE_UNDEFINED:=1
+  else
+   ifeq ($(SANITIZE),3)
+    SANITIZE_ADDRESS:=1
+    SANITIZE_UNDEFINED:=1
+   else
+    $(error Unknown value '$(SANITIZE)' specified for SANITIZE in config.makefile)
+   endif
+  endif
+ endif
+endif
+
+ifeq ($(SANITIZE_ADDRESS),1)
+ ifneq ('$(USE_GCC_48_OR_HIGHER)','yes')
+  $(info AddressSanitizer not usable with gcc $(COMPILER_VERSION) - disabled)
+  SANITIZE_ADDRESS:=0
+ else
+  ifneq ('$(USE_GCC_49_OR_HIGHER)','yes')
+   $(warning note that LeakSanitizer does not work with gcc $(COMPILER_VERSION))
+  endif
+ endif
+endif
+
+ifeq ($(SANITIZE_UNDEFINED),1)
+ ifneq ('$(USE_GCC_49_OR_HIGHER)','yes')
+  $(info UndefinedBehaviorSanitizer not usable with gcc $(COMPILER_VERSION) - disabled)
+  SANITIZE_UNDEFINED:=0
+ endif
 endif
 
 #---------------------- 32 or 64 bit
@@ -417,6 +500,27 @@ ifeq ('$(USE_GCC_48_OR_HIGHER)','yes')
  cflags += -fno-diagnostics-show-caret#gcc 4.8 (4.7.?)
 endif
 #cflags += -save-temps# uncomment to see preprocessor output
+
+#---------------------- various sanitizers
+
+COMMON_SANITIZE_FLAGS:=-ggdb3 -fno-omit-frame-pointer
+
+# activate AddressSanitizer+LeakSanitizer?
+ifeq ($(SANITIZE_ADDRESS),1)
+ cflags += $(COMMON_SANITIZE_FLAGS) -fsanitize=address
+ EXECLIBS += -lasan
+# EXECLIBS += -static-libasan
+endif
+
+# activate UndefinedBehaviorSanitizer?
+ifeq ($(SANITIZE_UNDEFINED),1)
+ cflags += $(COMMON_SANITIZE_FLAGS) -fsanitize=undefined
+ ifeq ('$(DEBUG)','1')
+# workaround https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63531
+  extended_cpp_warnings:=$(subst -Weffc++,,$(extended_cpp_warnings))
+ endif
+ EXECLIBS += -lubsan
+endif
 
 #---------------------- X11 location
 
@@ -756,6 +860,13 @@ endif
 
 # ---------------------------------------- check gcc version
 
+COMPILER_BROKEN:=0
+
+# gcc 4.8.0 produces invalid code (see #617)
+ifeq ('$(COMPILER_VERSION_ALLOWED)', '4.8.0') 
+COMPILER_BROKEN:=1
+endif
+
 check_same_GCC_VERSION:
 		$(ARBHOME)/SOURCE_TOOLS/check_same_compiler_version.pl $(COMPILER_NAME) $(COMPILER_VERSION_ALLOWED)
 
@@ -769,13 +880,15 @@ ifeq ('$(COMPILER_VERSION_ALLOWED)', '')
 		@echo '    - add your version to ALLOWED_$(COMPILER_NAME)_VERSIONS in the Makefile and try it out or'
 		@echo '    - switch to one of the allowed versions (see arb_README_gcc.txt for installing'
 		@echo '      a different version of gcc)'
-		@echo ''
-		@false
+		$(error Unsupported compiler '$(COMPILER_NAME)' version '$(COMPILER_VERSION)')
 else
+ifeq ($(COMPILER_BROKEN),1)
+		$(error $(COMPILER_NAME) version '$(COMPILER_VERSION_ALLOWED)' would build a broken ARB version. Compilation refused)
+else 
 		@echo "  - Supported $(COMPILER_NAME) version '$(COMPILER_VERSION_ALLOWED)' detected - fine!"
 		@echo ''
 		$(MAKE) check_same_GCC_VERSION
-
+endif
 endif
 
 #---------------------- check ARBHOME
@@ -813,7 +926,6 @@ check_TOOLS:
 		"$(MAKEDEPEND_PLAIN)" \
 		"$(LINK_SHARED_LIB)" \
 		"$(LINK_SHARED_LIB)" \
-
 
 check_ENVIRONMENT : check_PATH check_TOOLS
 		@echo "-------------------- Environment [start]"
@@ -1207,7 +1319,7 @@ ARCHS_PROBE_DEPEND = \
 		$(ARCHS_PT_SERVER) \
 
 $(PROBE): $(ARCHS_PROBE_DEPEND:.a=.dummy) link_db 
-	@SOURCE_TOOLS/binuptodate.pl $@ $(ARCHS_PROBE_LINK) $(ARBDB_LIB) $(ARCHS_CLIENT_PROBE) config.makefile $(use_ARB_main) || ( \
+	@SOURCE_TOOLS/binuptodate.pl $@ $(ARCHS_PROBE_LINK) $(ARBDB_LIB) $(ARCHS_SERVER_PROBE) config.makefile $(use_ARB_main) || ( \
 		echo "$(SEP) Link $@"; \
 		echo "$(LINK_EXECUTABLE) $@ $(use_ARB_main) $(LIBPATH) $(ARCHS_PROBE_LINK) $(ARBDB_LIB) $(ARCHS_SERVER_PROBE) $(SYSLIBS) $(EXECLIBS)" ; \
 		$(LINK_EXECUTABLE) $@ $(use_ARB_main) $(LIBPATH) $(ARCHS_PROBE_LINK) $(ARBDB_LIB) $(ARCHS_SERVER_PROBE) $(SYSLIBS) $(EXECLIBS) && \
@@ -1259,12 +1371,12 @@ addlibs:
 	@$(ARBHOME)/SOURCE_TOOLS/mv_if_diff $(@D)/Makefile.2 $(@D)/Makefile # update Makefile if changed
 
 %.proto:
-	@$(MAKE) -C $(@D) \
+	@($(MAKE) -C $(@D) \
 		"AUTODEPENDS=0" \
 		"MAIN=nothing" \
 		"cflags=noCflags" \
 		"cxxflags=noCxxflags" \
-		proto
+		proto 2>&1 ) | $(ARBHOME)/SOURCE_TOOLS/asan2msg.pl
 
 %.clean:
 	@$(MAKE) -C $(@D) \
