[REBASE] Rebasing from http://svn.mikro.biologie.tu-muenchen.de/svn/trunk@11130

diff --git a/branches/swig_bindings/GDEHELP/Makefile.helpfiles b/branches/swig_bindings/GDEHELP/Makefile.helpfiles
--- a/branches/swig_bindings/GDEHELP/Makefile.helpfiles
+++ b/branches/swig_bindings/GDEHELP/Makefile.helpfiles
@@ -24,66 +24,91 @@ info:
 ARBHOME=..
 GDE=$(ARBHOME)/GDE
 
+GENHELP_DEPENDS=genhelp.sh Makefile.helpfiles
+GENHELPTREE_DEPENDS=genhelptree.sh $(GENHELP_DEPENDS)
+
+# ---------- CLUSTALW
+
 CLUSTALW=$(GDE)/CLUSTALW
 CLUSTALW_HELP=$(CLUSTALW)/clustalw_help
 CLUSTALW_DOC=$(CLUSTALW)/clustalw.doc
 
-$(GENHELPDEST)/clustalw.help: $(CLUSTALW_HELP) $(CLUSTALW_DOC)
-	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $^
+$(GENHELPDEST)/clustalw.help: $(CLUSTALW_HELP) $(CLUSTALW_DOC) $(GENHELPTREE_DEPENDS)
+	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $(CLUSTALW_HELP) $(CLUSTALW_DOC)
+
+# ---------- AXML / FASTDNAML
 
 AXML_HELP=$(GDE)/AxML/AxML.doc
 FASTDNAML_DOC=$(GDE)/FASTDNAML/fastDNAml.doc
 
-$(GENHELPDEST)/dnaml.help: $(AXML_HELP) $(FASTDNAML_DOC)
-	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $^
+$(GENHELPDEST)/dnaml.help: $(AXML_HELP) $(FASTDNAML_DOC) $(GENHELPTREE_DEPENDS)
+	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $(AXML_HELP) $(FASTDNAML_DOC)
+
+# ---------- READSEQ
 
 READSEQ=$(ARBHOME)/READSEQ
 READSEQ_DOC_NAMES=Readme Formats Readseq.help
 READSEQ_DOCS=$(addprefix $(READSEQ)/,$(READSEQ_DOC_NAMES))
 
-$(GENHELPDEST)/readseq.help: $(READSEQ_DOCS)
-	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $^
+$(GENHELPDEST)/readseq.help: $(READSEQ_DOCS) $(GENHELPTREE_DEPENDS)
+	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $(READSEQ_DOCS)
+
+# ---------- PHYLIP
 
 PHYLIP_DISTANCE_HELP_NAMES=fitch kitsch neighbor dnadist protdist
 PHYLIP_DISTANCE_HELPS=$(addsuffix .doc,$(addprefix $(GENDOCDEST)/,$(PHYLIP_DISTANCE_HELP_NAMES)))
 
-$(GENHELPDEST)/phylip_distance.help: $(PHYLIP_DISTANCE_HELPS)
-	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $^
+$(GENHELPDEST)/phylip_distance.help: $(PHYLIP_DISTANCE_HELPS) $(GENHELPTREE_DEPENDS)
+	./genhelptree.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $(PHYLIP_DISTANCE_HELPS)
 
+# ------------------------------------------------------------
 # all help files in ./HELP_PLAIN are automatically found
 
-$(GENHELPDEST)/%.help: $(HELP_PLAIN)/%.help $(HEADER)
+$(GENHELPDEST)/%.help: $(HELP_PLAIN)/%.help $(HEADER) $(GENHELP_DEPENDS)
 	./genhelp.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $<
 
 # all help files in ./HELP_DOC_GEN are automatically found
 
-$(GENHELPDEST)/%.help: $(GENDOCDEST)/%.doc $(HEADER)
+$(GENHELPDEST)/%.help: $(GENDOCDEST)/%.doc $(HEADER) $(GENHELP_DEPENDS)
 	./genhelp.sh $@ "$(subst .help,,$(notdir $@))" $(HEADER) $<
 
 # ------------------------------------------------------------
 # rules to generate plain doc from provided html files
 
 HELP_TREEPUZZLE=../GDE/TREEPUZZLE/doc
-HELP_PHYLIP=../GDE/PHYLIP/doc
+PHYLIP_MAIN=../GDE/PHYLIP
+HELP_PHYLIP=$(PHYLIP_MAIN)/doc
 HELP_PHYML=../GDE/PHYML
 
-FORCED_DOC_NAMES=proml dnapars protpars phyml
+FORCED_DOC_NAMES=proml dnapars protpars phyml phylip
 LYNX_PARA=-dump -nolist -display_charset=iso-8859-1
 
 $(GENDOCDEST)/%.doc: $(HELP_PHYLIP)/%.html Makefile.helpfiles
-	lynx $(LYNX_PARA) $< | $(SED) -e 's/©/(C)/' > $@
-	test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@-test -f $@ && chmod u+w $@
+	(echo "# generated from ../$<"; lynx $(LYNX_PARA) $<) | $(SED) -e 's/©/(C)/' > $@
+	@test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@chmod a-w $@
 
 $(GENDOCDEST)/treepuzzle.doc: $(HELP_TREEPUZZLE)/manual.html Makefile.helpfiles
-	lynx $(LYNX_PARA) $< | $(SED) -e 's/©/(C)/' > $@
-	test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@-test -f $@ && chmod u+w $@
+	(echo "# generated from ../$<"; lynx $(LYNX_PARA) $<) | $(SED) -e 's/©/(C)/' > $@
+	@test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@chmod a-w $@
 
 $(GENDOCDEST)/phyml.doc: $(HELP_PHYML)/usersguide_phyliplike.html Makefile.helpfiles
-	lynx $(LYNX_PARA) $< | $(SED) -e 's/©/(C)/' > $@
-	test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@-test -f $@ && chmod u+w $@
+	(echo "# generated from ../$<"; lynx $(LYNX_PARA) $<) | $(SED) -e 's/©/(C)/' > $@
+	@test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@chmod a-w $@
+
+$(GENDOCDEST)/phylip.doc: $(PHYLIP_MAIN)/phylip.html Makefile.helpfiles
+	@-test -f $@ && chmod u+w $@
+	(echo "# generated from ../$<"; lynx $(LYNX_PARA) $<) | $(SED) -e 's/©/(C)/' > $@
+	@test -s $@ || (echo $@ not generated or empty && rm $@ && false)
+	@chmod a-w $@
 
 FORCED_DOCS=$(addsuffix .doc,$(addprefix $(GENDOCDEST)/,$(FORCED_DOC_NAMES)))
-forcedoc: $(FORCED_DOCS)
+forcedoc: $(FORCED_DOCS) Makefile
 
 # ------------------------------------------------------------
 # default rule to raise error if no rule is given to generate a helpfile.
@@ -94,7 +119,7 @@ $(GENHELPDEST)/%.help:
 	@( test -f $(HELP_WRITTEN)/$(notdir $@) ) \
 	|| \
 	( \
-		echo "Makefile.helpfiles:18: Error: No rule to make $(notdir $@) (to which is referred to in a GDE menu)" ; \
+		echo "Makefile.helpfiles:22: Error: No rule to make $(notdir $@) (to which is referred-to inside GDE menus, see hits below)" ; \
 		grep -n $(notdir $@) MENUS/*.menu ; \
 		false )
 
